travis:
  secure:
    BINSTAR_TOKEN: CnV+BqNd80Xxz+53CFGWeUP/8JRh6kDDEzKWnjMcHP+L9cmKNOXoxAUmYMEOKWqevUdS9ijoqXof8TGXu//GYy4/hASIjSWm2jTwN+Uj8OiD6BDqc/4/1fSXpVoUj25VgB8sNFIJIrVa9cnE0iiencYRF9dV1OOkxlm5+vBPB+zbOIaeJNqHkGCYtP0lN+cqjnCKWfc4DiBPgR/OU4UqVnRcv57F5JiN4lOj6Qp3Tc0drKf960sDVsKA2KHIArId/Xj/Lt+24sWvppL/2a4YbW829NQoWiZpIQ+3YjeBbrV0QiycLXl5OIJWxyCBQi/wjeou6vqQ5YSx0SS2DMrSkZucI1Hr0walV1uNg2r5I7eaVLnM4i68rrzcQIJWFeZN+iVsCDC8uTt4lSH5t5Fvgx+yKiDaHBOKxCRit069Qs/6EgIeJ7AuviW1vhZjQOal3FICGdOcCg41w1mcTWnhNUZ7rYyvP0XIWFAF8IR/ZXQ8u3XYTMpx3i0lE9orpbJuBWlhPmsdBMpS14j2BcRxNWBpN6pccPqEmHbLdCPBLjikIGCs7ROZXw/D0DqJMryqd4MeAuU6hh6J4kbLw7DAmDE4ybfjQ22XDYhcVluCLJoAfISa1Z/OBsqsnjbbfTgnM/UD2GRUTnZtLF/NwMvuWYvS/qUCmFZ2T/hQP30VigE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
